In [1]:
import pandas as pd
import numpy as np

from generate_results import make_results_df

In [2]:
dataset = 'inconel'
transfer_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 1

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,inconel,n/a,0.03099 (+/- 0.00000),0.03263 (+/- 0.00000),0.02565 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,inconel,from scratch,0.01338 (+/- 0.00276),0.01342 (+/- 0.00275),0.01002 (+/- 0.00239),13.2 (+/- 8.405950273467004)
TL - 1,inconel,stainless_steel,0.01217 (+/- 0.00040),0.01169 (+/- 0.00048),0.00910 (+/- 0.00039),33.3 (+/- 11.269871339105872)
TL - 2,stainless_steel,from scratch,0.03288 (+/- 0.00079),0.03150 (+/- 0.00097),0.04956 (+/- 0.00210),12.6 (+/- 7.57231800705702)
TL - 3,stainless_steel,stainless_steel,0.06826 (+/- 0.00004),0.06666 (+/- 0.00028),0.04715 (+/- 0.00045),10.45 (+/- 3.879110722833263)

In [4]:
dataset = 'stainless_steel'
transfer_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 1

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,stainless_steel,n/a,0.03392 (+/- 0.00000),0.03240 (+/- 0.00000),0.02726 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,stainless_steel,from scratch,0.02497 (+/- 0.00100),0.02343 (+/- 0.00103),0.01962 (+/- 0.00120),14.5 (+/- 7.419568720619818)
TL - 1,stainless_steel,inconel,0.02000 (+/- 0.00159),0.01935 (+/- 0.00177),0.01661 (+/- 0.00150),51.3 (+/- 18.34420889545254)
TL - 2,inconel,from scratch,0.02374 (+/- 0.00081),0.02287 (+/- 0.00094),0.09556 (+/- 0.00625),12.45 (+/- 11.359907570046508)
TL - 3,inconel,inconel,0.02332 (+/- 0.00031),0.02258 (+/- 0.00040),0.10956 (+/- 0.00295),30.8 (+/- 11.711532777565882)

In [5]:
dataset = 'inconel'
transfer_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 2

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,inconel,n/a,0.03099 (+/- 0.00000),0.03263 (+/- 0.00000),0.02565 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,inconel,from scratch,0.01338 (+/- 0.00276),0.01342 (+/- 0.00275),0.01002 (+/- 0.00239),13.2 (+/- 8.405950273467004)
TL - 1,inconel,stainless_steel,0.01285 (+/- 0.00030),0.01246 (+/- 0.00040),0.00963 (+/- 0.00027),39.4 (+/- 9.789790600416334)
TL - 2,stainless_steel,from scratch,0.03288 (+/- 0.00079),0.03150 (+/- 0.00097),0.04956 (+/- 0.00210),12.6 (+/- 7.57231800705702)
TL - 3,stainless_steel,stainless_steel,0.06834 (+/- 0.00004),0.06669 (+/- 0.00030),0.04654 (+/- 0.00025),11.0 (+/- 4.03732584763727)

In [6]:
dataset = 'stainless_steel'
transfer_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 2

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,stainless_steel,n/a,0.03392 (+/- 0.00000),0.03240 (+/- 0.00000),0.02726 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,stainless_steel,from scratch,0.02497 (+/- 0.00100),0.02343 (+/- 0.00103),0.01962 (+/- 0.00120),14.5 (+/- 7.419568720619818)
TL - 1,stainless_steel,inconel,0.01937 (+/- 0.00083),0.01860 (+/- 0.00095),0.01598 (+/- 0.00081),62.35 (+/- 18.881935811775232)
TL - 2,inconel,from scratch,0.02374 (+/- 0.00081),0.02287 (+/- 0.00094),0.09556 (+/- 0.00625),12.45 (+/- 11.359907570046508)
TL - 3,inconel,inconel,0.02455 (+/- 0.00022),0.02375 (+/- 0.00028),0.10973 (+/- 0.00260),30.5 (+/- 8.32165848854662)

In [7]:
dataset = 'inconel'
transfer_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 3

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,inconel,n/a,0.03099 (+/- 0.00000),0.03263 (+/- 0.00000),0.02565 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,inconel,from scratch,0.01338 (+/- 0.00276),0.01342 (+/- 0.00275),0.01002 (+/- 0.00239),13.2 (+/- 8.405950273467004)
TL - 1,inconel,stainless_steel,0.01786 (+/- 0.00034),0.01780 (+/- 0.00040),0.01443 (+/- 0.00030),57.25 (+/- 10.852994978345839)
TL - 2,stainless_steel,from scratch,0.03288 (+/- 0.00079),0.03150 (+/- 0.00097),0.04956 (+/- 0.00210),12.6 (+/- 7.57231800705702)
TL - 3,stainless_steel,stainless_steel,0.06846 (+/- 0.00003),0.06678 (+/- 0.00029),0.04612 (+/- 0.00018),9.3 (+/- 2.9171904291629644)

In [8]:
dataset = 'stainless_steel'
transfer_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_frozen = 3

df = make_results_df(dataset, transfer_dataset, results_dir, num_inverse_layers_frozen)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,stainless_steel,n/a,0.03392 (+/- 0.00000),0.03240 (+/- 0.00000),0.02726 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,stainless_steel,from scratch,0.02497 (+/- 0.00100),0.02343 (+/- 0.00103),0.01962 (+/- 0.00120),14.5 (+/- 7.419568720619818)
TL - 1,stainless_steel,inconel,0.02448 (+/- 0.00033),0.02339 (+/- 0.00042),0.02034 (+/- 0.00028),90.1 (+/- 16.697005719589367)
TL - 2,inconel,from scratch,0.02374 (+/- 0.00081),0.02287 (+/- 0.00094),0.09556 (+/- 0.00625),12.45 (+/- 11.359907570046508)
TL - 3,inconel,inconel,0.02591 (+/- 0.00005),0.02512 (+/- 0.00008),0.10307 (+/- 0.00105),16.85 (+/- 7.295717922178735)