In [1]:
import pandas as pd
import numpy as np

from generate_results import make_results_df

In [2]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03099 (+/- 0.00000),0.03263 (+/- 0.00000),0.02565 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02044 (+/- 0.00000),0.02029 (+/- 0.00000),0.01538 (+/- 0.00000),55.0 (+/- 0.00)
Standard,inconel,from_scratch,0.04493 (+/- 0.00000),0.04389 (+/- 0.00000),0.03943 (+/- 0.00000),79.0 (+/- 0.00)
TL - 1,from_scratch,stainless_steel,0.01471 (+/- 0.00000),0.01467 (+/- 0.00000),0.08157 (+/- 0.00000),55.0 (+/- 0.00)
TL - 2,stainless_steel,stainless_steel,0.01915 (+/- 0.00000),0.01838 (+/- 0.00000),0.08102 (+/- 0.00000),29.0 (+/- 0.00)

In [3]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03392 (+/- 0.00000),0.03240 (+/- 0.00000),0.02726 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02582 (+/- 0.00000),0.02422 (+/- 0.00000),0.02127 (+/- 0.00000),54.0 (+/- 0.00)
Standard,stainless_steel,from_scratch,0.02583 (+/- 0.00000),0.02501 (+/- 0.00000),0.02019 (+/- 0.00000),55.0 (+/- 0.00)
TL - 1,from_scratch,inconel,0.02468 (+/- 0.00000),0.02444 (+/- 0.00000),0.12952 (+/- 0.00000),56.0 (+/- 0.00)
TL - 2,inconel,inconel,0.01901 (+/- 0.00000),0.01885 (+/- 0.00000),0.12938 (+/- 0.00000),58.0 (+/- 0.00)