In [1]:
import pandas as pd
import numpy as np

from generate_results import make_results_df

In [2]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_stainless_steel.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_hot_start_stainless_steel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.02709 (+/- 0.00000),0.02755 (+/- 0.00000),0.02145 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,stainless_steel,n/a,0.02697 (+/- 0.00000),0.02774 (+/- 0.00000),0.02201 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.01460 (+/- 0.00000),0.01413 (+/- 0.00000),0.01145 (+/- 0.00000),76.0 (+/- 0.00)
Standard,inconel,from_scratch,0.05372 (+/- 0.00000),0.05233 (+/- 0.00000),0.04952 (+/- 0.00000),11.0 (+/- 0.00)
TL - 1,from_scratch,stainless_steel,0.01449 (+/- 0.00000),0.01400 (+/- 0.00000),0.01105 (+/- 0.00000),87.0 (+/- 0.00)
TL - 2,stainless_steel,stainless_steel,0.02302 (+/- 0.00000),0.02283 (+/- 0.00000),0.01864 (+/- 0.00000),32.0 (+/- 0.00)

In [3]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1


df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_inconel.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_hot_start_inconel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03525 (+/- 0.00000),0.03434 (+/- 0.00000),0.02893 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,inconel,n/a,0.03316 (+/- 0.00000),0.03238 (+/- 0.00000),0.02623 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02583 (+/- 0.00000),0.02422 (+/- 0.00000),0.02134 (+/- 0.00000),53.0 (+/- 0.00)
Standard,stainless_steel,from_scratch,0.01881 (+/- 0.00000),0.01830 (+/- 0.00000),0.01592 (+/- 0.00000),55.0 (+/- 0.00)
TL - 1,from_scratch,inconel,0.02576 (+/- 0.00000),0.02468 (+/- 0.00000),0.02187 (+/- 0.00000),30.0 (+/- 0.00)
TL - 2,inconel,inconel,0.02525 (+/- 0.00000),0.02445 (+/- 0.00000),0.01974 (+/- 0.00000),48.0 (+/- 0.00)