In [1]:
import pandas as pd
import numpy as np

from scripts.generate_results_table import make_results_df

In [2]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['../results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_stainless_steel.json', '../results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_hot_start_stainless_steel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.02709 (+/- 0.00000),0.02755 (+/- 0.00000),0.02145 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,stainless_steel,n/a,0.02697 (+/- 0.00000),0.02774 (+/- 0.00000),0.02201 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.01637 (+/- 0.00149),0.01671 (+/- 0.00174),0.01364 (+/- 0.00138),75.4 (+/- 17.41)
Standard,stainless_steel,from_scratch,0.02118 (+/- 0.00144),0.02102 (+/- 0.00147),0.01730 (+/- 0.00126),55.35 (+/- 17.47)
TL - 1,from_scratch,stainless_steel,0.01588 (+/- 0.00187),0.01584 (+/- 0.00179),0.01241 (+/- 0.00149),59.65 (+/- 14.21)
TL - 2,stainless_steel,stainless_steel,0.02623 (+/- 0.01263),0.02638 (+/- 0.01253),0.02204 (+/- 0.01219),57.4 (+/- 13.93)

In [3]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1


df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['../results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_inconel.json', '../results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_hot_start_inconel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03525 (+/- 0.00000),0.03434 (+/- 0.00000),0.02893 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,inconel,n/a,0.03316 (+/- 0.00000),0.03238 (+/- 0.00000),0.02623 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02602 (+/- 0.00041),0.02545 (+/- 0.00039),0.02170 (+/- 0.00048),51.9 (+/- 11.24)
Standard,inconel,from_scratch,0.02695 (+/- 0.00137),0.02648 (+/- 0.00150),0.02194 (+/- 0.00171),55.15 (+/- 14.22)
TL - 1,from_scratch,inconel,0.02490 (+/- 0.00039),0.02453 (+/- 0.00055),0.02079 (+/- 0.00062),62.8 (+/- 18.67)
TL - 2,inconel,inconel,0.02201 (+/- 0.00316),0.02159 (+/- 0.00289),0.01784 (+/- 0.00184),64.45 (+/- 17.95)

In [4]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 2
num_forward_layers_transferred = 2

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['../results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_2_layers_stainless_steel_hot_start_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_stainless_steel.json', '../results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_2_layers_stainless_steel_hot_start_inverseDNN_hot_start_stainless_steel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.02709 (+/- 0.00000),0.02755 (+/- 0.00000),0.02145 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,stainless_steel,n/a,0.03004 (+/- 0.00000),0.03165 (+/- 0.00000),0.02497 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.01637 (+/- 0.00149),0.01671 (+/- 0.00174),0.01364 (+/- 0.00138),75.4 (+/- 17.41)
Standard,stainless_steel,from_scratch,0.02209 (+/- 0.00804),0.02219 (+/- 0.00802),0.01846 (+/- 0.00772),65.35 (+/- 21.92)
TL - 1,from_scratch,stainless_steel,0.01610 (+/- 0.00240),0.01606 (+/- 0.00231),0.01263 (+/- 0.00184),53.75 (+/- 16.14)
TL - 2,stainless_steel,stainless_steel,0.01905 (+/- 0.00252),0.01891 (+/- 0.00241),0.01551 (+/- 0.00213),66.15 (+/- 31.82)

In [7]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 2
num_forward_layers_transferred = 2


df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['../results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_2_layers_inconel_hot_start_inverseDNN_from_scratch.json', '../results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_inconel.json', '../results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_2_layers_inconel_hot_start_inverseDNN_hot_start_inconel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03525 (+/- 0.00000),0.03434 (+/- 0.00000),0.02893 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,inconel,n/a,0.03899 (+/- 0.00000),0.03873 (+/- 0.00000),0.03126 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02602 (+/- 0.00041),0.02545 (+/- 0.00039),0.02170 (+/- 0.00048),51.9 (+/- 11.24)
Standard,inconel,from_scratch,0.02612 (+/- 0.00271),0.02561 (+/- 0.00263),0.02062 (+/- 0.00234),50.15 (+/- 15.77)
TL - 1,from_scratch,inconel,0.02521 (+/- 0.00101),0.02459 (+/- 0.00092),0.02062 (+/- 0.00049),54.95 (+/- 10.97)
TL - 2,inconel,inconel,0.02636 (+/- 0.00339),0.02588 (+/- 0.00323),0.02069 (+/- 0.00321),72.85 (+/- 20.51)