In [1]:
import pandas as pd
import numpy as np

from generate_results import make_results_df

In [2]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_stainless_steel.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_1_layers_stainless_steel_hot_start_inverseDNN_hot_start_stainless_steel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.02709 (+/- 0.00000),0.02755 (+/- 0.00000),0.02145 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,stainless_steel,n/a,0.02697 (+/- 0.00000),0.02774 (+/- 0.00000),0.02201 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.01637 (+/- 0.00149),0.01671 (+/- 0.00174),0.01364 (+/- 0.00138),75.4 (+/- 17.41)
Standard,stainless_steel,from_scratch,0.02118 (+/- 0.00144),0.02102 (+/- 0.00147),0.01730 (+/- 0.00126),55.35 (+/- 17.47)
TL - 1,from_scratch,stainless_steel,0.02522 (+/- 0.01609),0.02521 (+/- 0.01596),0.02139 (+/- 0.01500),72.3 (+/- 21.69)
TL - 2,stainless_steel,stainless_steel,0.02554 (+/- 0.01204),0.02558 (+/- 0.01202),0.02151 (+/- 0.01171),68.4 (+/- 18.18)

In [4]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 1
num_forward_layers_transferred = 1


df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_inconel.json', 'results/inc_ss/standard_loss/1_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_1_layers_inconel_hot_start_inverseDNN_hot_start_inconel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03525 (+/- 0.00000),0.03434 (+/- 0.00000),0.02893 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,inconel,n/a,0.03316 (+/- 0.00000),0.03238 (+/- 0.00000),0.02623 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02602 (+/- 0.00041),0.02545 (+/- 0.00039),0.02170 (+/- 0.00048),51.9 (+/- 11.24)
Standard,inconel,from_scratch,0.02695 (+/- 0.00137),0.02648 (+/- 0.00150),0.02194 (+/- 0.00171),55.15 (+/- 14.22)
TL - 1,from_scratch,inconel,0.02532 (+/- 0.00126),0.02475 (+/- 0.00114),0.02069 (+/- 0.00071),57.85 (+/- 17.93)
TL - 2,inconel,inconel,0.02229 (+/- 0.00310),0.02179 (+/- 0.00268),0.01757 (+/- 0.00151),60.05 (+/- 14.79)

In [5]:
dataset = 'inconel'
hot_start_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 2
num_forward_layers_transferred = 2

df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_inconel_dataset_forwardDNN_2_layers_stainless_steel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_stainless_steel.json', 'results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_inconel_dataset_forwardDNN_2_layers_stainless_steel_hot_start_inverseDNN_hot_start_stainless_steel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.02709 (+/- 0.00000),0.02755 (+/- 0.00000),0.02145 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,stainless_steel,n/a,0.02697 (+/- 0.00000),0.02774 (+/- 0.00000),0.02201 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.01637 (+/- 0.00149),0.01671 (+/- 0.00174),0.01364 (+/- 0.00138),75.4 (+/- 17.41)
Standard,stainless_steel,from_scratch,0.02209 (+/- 0.00804),0.02219 (+/- 0.00802),0.01846 (+/- 0.00772),65.35 (+/- 21.92)
TL - 1,from_scratch,stainless_steel,0.01541 (+/- 0.00160),0.01535 (+/- 0.00165),0.01210 (+/- 0.00124),64.1 (+/- 13.65)
TL - 2,stainless_steel,stainless_steel,0.01972 (+/- 0.00240),0.01964 (+/- 0.00232),0.01608 (+/- 0.00205),55.45 (+/- 25.19)

In [6]:
dataset = 'stainless_steel'
hot_start_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'
num_inverse_layers_transferred = 2
num_forward_layers_transferred = 2


df = make_results_df(dataset, hot_start_dataset, results_dir, num_inverse_layers_transferred, num_forward_layers_transferred)
df

['results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/standard_stainless_steel_dataset_forwardDNN_2_layers_inconel_hot_start_inverseDNN_from_scratch.json', 'results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_from_scratch_inverseDNN_hot_start_inconel.json', 'results/inc_ss/standard_loss/2_layers_transferred/transfer_learning_stainless_steel_dataset_forwardDNN_2_layers_inconel_hot_start_inverseDNN_hot_start_inconel.json']

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,from_scratch,n/a,0.03525 (+/- 0.00000),0.03434 (+/- 0.00000),0.02893 (+/- 0.00000),0.0 (+/- 0.00)
Forward Model,inconel,n/a,0.03316 (+/- 0.00000),0.03238 (+/- 0.00000),0.02623 (+/- 0.00000),0.0 (+/- 0.00)
Standard,from_scratch,from_scratch,0.02602 (+/- 0.00041),0.02545 (+/- 0.00039),0.02170 (+/- 0.00048),51.9 (+/- 11.24)
Standard,inconel,from_scratch,0.02612 (+/- 0.00271),0.02561 (+/- 0.00263),0.02062 (+/- 0.00234),50.15 (+/- 15.77)
TL - 1,from_scratch,inconel,0.02422 (+/- 0.00204),0.02369 (+/- 0.00196),0.02003 (+/- 0.00161),57.05 (+/- 16.46)
TL - 2,inconel,inconel,0.02559 (+/- 0.00430),0.02521 (+/- 0.00411),0.02043 (+/- 0.00372),74.05 (+/- 27.36)